#ifndef SECRETS_H
#define SECRETS_H

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define DEEPGRAM_API_KEY "YOUR_DEEPGRAM_API_KEY"
#define GEMINI_API_KEY "YOUR_GEMINI_API_KEY"

#endif
